"""dodata kolona attachmet_paths u Application

Revision ID: 9220ae9d2154
Revises: 964efa3f0abc
Create Date: 2025-06-08 09:28:49.111535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9220ae9d2154'
down_revision = '964efa3f0abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_backup')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_paths', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('attachment_paths')

    op.create_table('application_backup',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('children_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('children_surname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mother_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('mother_surname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('father_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('father_surname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('grade', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('class_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('has_documents', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('document_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('consent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_submitted', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
